enterprise/multinetwork: Fix resource.Store interface
Follow commit 422670134396 ("resource: Add support for releasable
resources"). This fixes the following error on the latest main-ce sync
pulling it that change:

Error: enterprise/pkg/multinetwork/manager_test.go:70:13: cannot use mockStore[*slim_core_v1.Pod]{…} (value of type mockStore[*"github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1".Pod]) as "github.com/cilium/cilium/pkg/k8s/resource".Store[*"github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1".Pod] value in struct literal: mockStore[*"github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1".Pod] does not implement "github.com/cilium/cilium/pkg/k8s/resource".Store[*"github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1".Pod] (missing method Release)

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>